### ISSUE TITLE
How can I add new subjects and where ?

### ISSUE THREAD

**Issue by jokera666** [campusdomar/PuMuKIT2#122]
Hello , I'm new with the platform. I want to know where I can add new subject in the subjects list. When I list the databese in mongo i get this tables (controllers):
 Broadcast
Job
MultimediaObject
PermissionProfile
Person
Role
Series
Tag
User
ViewsLog
system.indexes

**Comment by Alfro** [comment]
The "Tag" table is what you are looking for. "Subjects" are included in the "Tag" document. Although I would not recommend adding them through the mongodb if you are new with the platform, since an incorrect structure can lead to unexpected errors.

I would recommend you to use the back-office. Go to Tables > Tags:
![](https://raw.githubusercontent.com/campusdomar/PuMuKIT2-doc/master/images/PuMuKit_2_Content_Admin_Guide_v1.1_html_305eb328.png)

**Comment by Alfro** [comment]
@jokera666 I assume everything is clear. I will close the issue now. :smile:
